// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: google/protobuf/extend/http.proto

package httppb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Http struct {
	// Types that are valid to be assigned to Pattern:
	//	*Http_Get
	//	*Http_Put
	//	*Http_Post
	//	*Http_Delete
	Pattern isHttp_Pattern `protobuf_oneof:"pattern"`
	// rpc desc
	Desc string `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	// content-type for request
	Consume string `protobuf:"bytes,6,opt,name=consume,proto3" json:"consume,omitempty"`
	// content-type for response
	Produce              string   `protobuf:"bytes,7,opt,name=produce,proto3" json:"produce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Http) Reset()         { *m = Http{} }
func (m *Http) String() string { return proto.CompactTextString(m) }
func (*Http) ProtoMessage()    {}
func (*Http) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc0b6f560ba9f6fa, []int{0}
}
func (m *Http) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Http.Unmarshal(m, b)
}
func (m *Http) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Http.Marshal(b, m, deterministic)
}
func (m *Http) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Http.Merge(m, src)
}
func (m *Http) XXX_Size() int {
	return xxx_messageInfo_Http.Size(m)
}
func (m *Http) XXX_DiscardUnknown() {
	xxx_messageInfo_Http.DiscardUnknown(m)
}

var xxx_messageInfo_Http proto.InternalMessageInfo

type isHttp_Pattern interface {
	isHttp_Pattern()
}

type Http_Get struct {
	Get string `protobuf:"bytes,1,opt,name=get,proto3,oneof" json:"get,omitempty"`
}
type Http_Put struct {
	Put string `protobuf:"bytes,2,opt,name=put,proto3,oneof" json:"put,omitempty"`
}
type Http_Post struct {
	Post string `protobuf:"bytes,3,opt,name=post,proto3,oneof" json:"post,omitempty"`
}
type Http_Delete struct {
	Delete string `protobuf:"bytes,4,opt,name=delete,proto3,oneof" json:"delete,omitempty"`
}

func (*Http_Get) isHttp_Pattern()    {}
func (*Http_Put) isHttp_Pattern()    {}
func (*Http_Post) isHttp_Pattern()   {}
func (*Http_Delete) isHttp_Pattern() {}

func (m *Http) GetPattern() isHttp_Pattern {
	if m != nil {
		return m.Pattern
	}
	return nil
}

func (m *Http) GetGet() string {
	if x, ok := m.GetPattern().(*Http_Get); ok {
		return x.Get
	}
	return ""
}

func (m *Http) GetPut() string {
	if x, ok := m.GetPattern().(*Http_Put); ok {
		return x.Put
	}
	return ""
}

func (m *Http) GetPost() string {
	if x, ok := m.GetPattern().(*Http_Post); ok {
		return x.Post
	}
	return ""
}

func (m *Http) GetDelete() string {
	if x, ok := m.GetPattern().(*Http_Delete); ok {
		return x.Delete
	}
	return ""
}

func (m *Http) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Http) GetConsume() string {
	if m != nil {
		return m.Consume
	}
	return ""
}

func (m *Http) GetProduce() string {
	if m != nil {
		return m.Produce
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Http) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Http_Get)(nil),
		(*Http_Put)(nil),
		(*Http_Post)(nil),
		(*Http_Delete)(nil),
	}
}

var E_Http = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.MethodOptions)(nil),
	ExtensionType: (*Http)(nil),
	Field:         1995,
	Name:          "google.protobuf.extends.http",
	Tag:           "bytes,1995,opt,name=http",
	Filename:      "google/protobuf/extend/http.proto",
}

func init() {
	proto.RegisterType((*Http)(nil), "google.protobuf.extends.Http")
	proto.RegisterExtension(E_Http)
}

func init() { proto.RegisterFile("google/protobuf/extend/http.proto", fileDescriptor_cc0b6f560ba9f6fa) }

var fileDescriptor_cc0b6f560ba9f6fa = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4a, 0x33, 0x31,
	0x10, 0xc7, 0xbf, 0xb4, 0xfb, 0xb5, 0x34, 0x1e, 0x84, 0x20, 0x18, 0x0a, 0x4a, 0xf5, 0xd4, 0x53,
	0x16, 0xd4, 0x93, 0xde, 0x0a, 0x62, 0x2f, 0x62, 0x59, 0x3c, 0x88, 0xb7, 0xee, 0xee, 0xb8, 0xbb,
	0xd0, 0xee, 0x0c, 0xc9, 0x04, 0xf4, 0x75, 0x7c, 0x03, 0x9f, 0xc3, 0x17, 0xf2, 0x28, 0xc9, 0x6e,
	0x11, 0x0a, 0x3d, 0x25, 0xff, 0xdf, 0xfc, 0x92, 0x30, 0x13, 0x79, 0x51, 0x21, 0x56, 0x1b, 0x48,
	0xc9, 0x22, 0x63, 0xee, 0xdf, 0x52, 0x78, 0x67, 0x68, 0xcb, 0xb4, 0x66, 0x26, 0x13, 0xa1, 0x3a,
	0xed, 0x14, 0xb3, 0x53, 0x4c, 0xa7, 0xb8, 0xe9, 0x6c, 0xff, 0x6c, 0x09, 0xae, 0xb0, 0x0d, 0x31,
	0xda, 0x4e, 0xbe, 0xfc, 0x12, 0x32, 0x59, 0x32, 0x93, 0x52, 0x72, 0x58, 0x01, 0x6b, 0x31, 0x13,
	0xf3, 0xc9, 0xf2, 0x5f, 0x16, 0x42, 0x60, 0xe4, 0x59, 0x0f, 0x76, 0x8c, 0x3c, 0xab, 0x13, 0x99,
	0x10, 0x3a, 0xd6, 0xc3, 0x1e, 0xc6, 0xa4, 0xb4, 0x1c, 0x95, 0xb0, 0x01, 0x06, 0x9d, 0xf4, 0xbc,
	0xcf, 0x4a, 0xc9, 0x24, 0x3c, 0xaa, 0xff, 0x07, 0x9e, 0xc5, 0xbd, 0xd2, 0x72, 0x5c, 0x60, 0xeb,
	0xfc, 0x16, 0xf4, 0x28, 0xe2, 0x5d, 0x0c, 0x15, 0xb2, 0x58, 0xfa, 0x02, 0xf4, 0xb8, 0xab, 0xf4,
	0x71, 0x31, 0x91, 0x63, 0x5a, 0x33, 0x83, 0x6d, 0x6f, 0x33, 0x99, 0x84, 0xe6, 0xd5, 0xb9, 0xd9,
	0xef, 0xfb, 0x11, 0xb8, 0xc6, 0xf2, 0x89, 0xb8, 0xc1, 0xd6, 0xe9, 0xef, 0xe3, 0x99, 0x98, 0x1f,
	0x5d, 0x9d, 0x99, 0x03, 0xe3, 0x31, 0xa1, 0xf1, 0x2c, 0xde, 0xb5, 0x68, 0xe4, 0xb4, 0xc0, 0xed,
	0x01, 0x73, 0x31, 0x09, 0xe6, 0x2a, 0xc0, 0x95, 0x78, 0xbd, 0xa9, 0x1a, 0xae, 0x7d, 0x6e, 0x0a,
	0xdc, 0xa6, 0x45, 0xbd, 0xb6, 0x1b, 0x70, 0xf9, 0xda, 0x81, 0xfb, 0x9b, 0x32, 0x7f, 0x10, 0xb8,
	0xf8, 0x41, 0x94, 0xdf, 0x75, 0xcb, 0x8f, 0x10, 0x9f, 0x83, 0xe4, 0xe1, 0xfe, 0xe5, 0x39, 0x1f,
	0x45, 0xef, 0xfa, 0x37, 0x00, 0x00, 0xff, 0xff, 0x4b, 0xec, 0x16, 0xf1, 0xd9, 0x01, 0x00, 0x00,
}
