// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: google/protobuf/extends/service.proto

package servicepb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Service struct {
	Host                 string         `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string         `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Header               *ServiceHeader `protobuf:"bytes,4,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_9178b1bd44f4edc3, []int{0}
}
func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Service) GetHeader() *ServiceHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type ServiceHeader struct {
	Auth                 string   `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceHeader) Reset()         { *m = ServiceHeader{} }
func (m *ServiceHeader) String() string { return proto.CompactTextString(m) }
func (*ServiceHeader) ProtoMessage()    {}
func (*ServiceHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_9178b1bd44f4edc3, []int{1}
}
func (m *ServiceHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceHeader.Unmarshal(m, b)
}
func (m *ServiceHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceHeader.Marshal(b, m, deterministic)
}
func (m *ServiceHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceHeader.Merge(m, src)
}
func (m *ServiceHeader) XXX_Size() int {
	return xxx_messageInfo_ServiceHeader.Size(m)
}
func (m *ServiceHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceHeader proto.InternalMessageInfo

func (m *ServiceHeader) GetAuth() string {
	if m != nil {
		return m.Auth
	}
	return ""
}

var E_Srv = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
	ExtensionType: (*Service)(nil),
	Field:         1995,
	Name:          "google.protobuf.extends.srv",
	Tag:           "bytes,1995,opt,name=srv",
	Filename:      "google/protobuf/extends/service.proto",
}

func init() {
	proto.RegisterType((*Service)(nil), "google.protobuf.extends.Service")
	proto.RegisterType((*ServiceHeader)(nil), "google.protobuf.extends.ServiceHeader")
	proto.RegisterExtension(E_Srv)
}

func init() {
	proto.RegisterFile("google/protobuf/extends/service.proto", fileDescriptor_9178b1bd44f4edc3)
}

var fileDescriptor_9178b1bd44f4edc3 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4d, 0xcf, 0xcf, 0x4f,
	0xcf, 0x49, 0xd5, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x4f, 0xad, 0x28, 0x49,
	0xcd, 0x4b, 0x29, 0xd6, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x03, 0x4b, 0x08, 0x89,
	0x43, 0x94, 0xe9, 0xc1, 0x94, 0xe9, 0x41, 0x95, 0x49, 0x29, 0xa0, 0xeb, 0x4f, 0x49, 0x2d, 0x4e,
	0x2e, 0xca, 0x2c, 0x28, 0xc9, 0x2f, 0x82, 0x28, 0x56, 0x6a, 0x65, 0xe4, 0x62, 0x0f, 0x86, 0x18,
	0x26, 0x24, 0xc4, 0xc5, 0x92, 0x91, 0x5f, 0x5c, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04,
	0x66, 0x83, 0xc4, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x98, 0x20, 0x62, 0x20, 0x36, 0x48, 0x0c, 0x64,
	0x8e, 0x04, 0x33, 0x44, 0x0c, 0xc4, 0x16, 0xb2, 0xe3, 0x62, 0xcb, 0x48, 0x4d, 0x4c, 0x49, 0x2d,
	0x92, 0x60, 0x51, 0x60, 0xd4, 0xe0, 0x36, 0x52, 0xd3, 0xc3, 0xe1, 0x26, 0x3d, 0xa8, 0x6d, 0x1e,
	0x60, 0xd5, 0x41, 0x50, 0x5d, 0x4a, 0xca, 0x5c, 0xbc, 0x28, 0x12, 0x20, 0x4b, 0x12, 0x4b, 0x4b,
	0x32, 0x60, 0x8e, 0x01, 0xb1, 0xad, 0x42, 0xb8, 0x98, 0x8b, 0x8b, 0xca, 0x84, 0xe4, 0x31, 0xcc,
	0x86, 0x6a, 0xf5, 0x2f, 0x28, 0xc9, 0xcc, 0xcf, 0x2b, 0x96, 0x38, 0xcd, 0x0f, 0x76, 0x83, 0x02,
	0x21, 0x37, 0x04, 0x81, 0x8c, 0x73, 0x2a, 0xe6, 0x92, 0x4e, 0xce, 0xcf, 0xc5, 0xa5, 0xd6, 0x89,
	0x07, 0xaa, 0x38, 0x00, 0x24, 0x11, 0xc0, 0x18, 0x65, 0x95, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4,
	0x97, 0x9c, 0x9f, 0xab, 0x9f, 0x9c, 0x91, 0x58, 0x94, 0x93, 0x5a, 0x9c, 0x94, 0x58, 0x9c, 0x5a,
	0x8c, 0x08, 0xe4, 0x92, 0xca, 0x82, 0x54, 0x78, 0x14, 0x15, 0x24, 0x59, 0xc3, 0x59, 0x3f, 0x18,
	0x19, 0x17, 0x31, 0xb1, 0xb8, 0xbb, 0x46, 0x84, 0x24, 0xb1, 0x81, 0x55, 0x1b, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x76, 0x03, 0x93, 0x1a, 0xe2, 0x01, 0x00, 0x00,
}
